project:
  uuid: 05d5247c-e400-42aa-8948-86bc2c5e955d
  slug: jdr-app
  node_id: a9b8efda5e21
  build_id: 996f2ae6-731f-5082-89f0-9b2e32d9897e
vcs:
  type: git
agents:
  available:
  - claude
  auto_commit: true
  lint_on_edit: false
